name: hugo website deploy

on:
  push:
    branches:
      - master  # push 到 master 分支时触发 jobs

jobs:
  deploy:
    # 将作业配置为在最新版本的 Ubuntu Linux 运行器上运行,非自己的服务器版本
    runs-on: ubuntu-22.04
    steps:
      # 检出代码
      - uses: actions/checkout@v4
        with:
          submodules: true  # 更新子模块（hugo themes）
          fetch-depth: 0

      # 配置 Hugo 环境
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 0.115.2
          extended: true
          # 配置node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          # 配置缓存
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Run Node
        run: npm ci

      # build hugo
      - name: Build website with Hugo
        run: hugo --minify --printI18nWarnings

        # 部署网站到ecs
      - name: Deploy website with rsync
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --quiet --delete
          path: public/
          remote_path: /www/wwwroot/www.loadingspace.cn/
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_KEY }}
