name: hugo website deploy

on:
  push:
    branches:
      - master  # push 到 master 分支时触发 jobs

jobs:
  deploy:
    # 将作业配置为在最新版本的 Ubuntu Linux 运行器上运行,非自己的服务器版本
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # 更新子模块（hugo themes）
          fetch-depth: 0

      # 配置 Hugo 环境
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.115.2
          extended: true

      # 构建 Hugo 静态页面
      - name: Build
        run: hugo --minify

      # 将静态页面部署至 ECS
      - name: Deploy to ECS
        # scp方式
        # uses: garygrossgarten/github-action-scp@release # 使用 scp 工具将静态页面远程复制到 ECS
        # ftp方式
        uses: sand4rt/ftp-deployer@v1.7 # 使用 ftp 工具将静态页面远程复制到 ECS
        with:
          # scp方式
          # local: public                                 # 待复制的本地文件路径
          # remote: /www/wwwroot/www.loadingspace.cn                      # ECS 路径
          # host: ${{ secrets.HOST }}                     # ECS 域名 或 IP 地址
          # username: ${{ secrets.SSH_USERNAME }}         # 登录用户名
          # password: ${{ secrets.SSH_PWD }}         # 登录密码
          # port: ${{ secrets.PORT }}                 # scp 端口号（默认 22）

          # ftp方式
          # server: ${{ secrets.HOST }}
          # username: ${{ secrets.FTP_NAME }}
          # password: ${{ secrets.FTP_PWD }}
          # local-dir: public/
          # server-dir: ./bak/
          
          sftp: false # optional
          host: 110.42.133.225 # e.g. ftp.host.com or sftp.host.com (without ftp:// or ftps://)
          port: 21 # optional, default is: 21
          username: ${{ secrets.FTP_NAME }} # FTP username
          password: ${{ secrets.FTP_PWD }} # FTP password
          remote_folder: /bak # optional, remote path of your FTP server
          local_folder: public # optional, local path, default is: dist
          cleanup: false # optional, remove existing files inside FTP remote folder
          #include: '[]' # optional, e.g. '['dist']'
          #exclude: '[]' # optional, e.g. '['node_modules/**', '.git/**', '*.env']'
          passive: true # optional
